using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._UM.Ghost;

[GenerateTypedNameReferences]
public sealed partial class GhostGroupCounter : Control
{
    private static int FontSize = 18;

    private Color _color;

    public GhostGroupCounter(Color color)
    {
        RobustXamlLoader.Load(this);

        _color = color;

        var msg = new FormattedMessage();
        msg.PushTag(new MarkupNode("font",
            new MarkupParameter("PikminCounter"),
            new Dictionary<string, MarkupParameter>()
            {
                { "size", new MarkupParameter(FontSize) }
            }));
        msg.PushColor(_color);
        msg.AddMarkupOrThrow("—"); //hardcode em dash lolol
        msg.Pop();
        msg.Pop();
        Bar.SetMessage(msg, tagsAllowed: [typeof(FontTag), typeof(ColorTag)]);

        SetText(0, 0);
    }

    public void SetText(int? amount, int? requiredAmount)
    {
        if (amount is not null)
        {
            var msg = new FormattedMessage();

            msg.PushTag(new MarkupNode("font",
                new MarkupParameter("PikminCounter"),
                new Dictionary<string, MarkupParameter>()
                {
                    { "size", new MarkupParameter(FontSize) }
                }));

            msg.PushColor(_color);

            msg.AddMarkupOrThrow(amount.Value.ToString());
            msg.Pop();
            msg.Pop();

            Amount.Margin = new Thickness(0, 0, 0, Bar.DesiredSize.X * 0.5f);
            Amount.SetMessage(msg, tagsAllowed: [typeof(FontTag), typeof(ColorTag)]);
        }

        if (requiredAmount is not null)
        {
            var msg = new FormattedMessage();

            msg.PushTag(new MarkupNode("font",
                new MarkupParameter("PikminCounter"),
                new Dictionary<string, MarkupParameter>()
                {
                    { "size", new MarkupParameter(FontSize) }
                }));

            msg.PushColor(_color);

            msg.AddMarkupOrThrow(requiredAmount.Value.ToString());
            msg.Pop();
            msg.Pop();

            RequiredAmount.Margin = new Thickness(0, -4, 0, 0);
            RequiredAmount.SetMessage(msg, tagsAllowed: [typeof(FontTag), typeof(ColorTag)]);
        }
    }

}

