using Content.Shared._UM.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._UM.Ghost;

[GenerateTypedNameReferences]
public sealed partial class GhostVoteContainer : Control
{
    public SortedDictionary<GhostGroupAction, GhostGroupCounter> Votes = new();

    private readonly SpriteSystem _spriteSystem;

    public GhostVoteContainer()
    {
        RobustXamlLoader.Load(this);
        var entManager = IoCManager.Resolve<IEntityManager>();
        _spriteSystem = entManager.System<SpriteSystem>();
    }

    public void UpdateVote(SortedDictionary<GhostGroupAction, List<EntityUid>> currentVotes, int required)
    {
        List<GhostGroupAction> removed = new();

        foreach (var (action, counter) in Votes)
        {
            if (!currentVotes.ContainsKey(action))
            {
                Container.RemoveChild(counter);
                removed.Add(action);
            }
        }

        foreach (var remove in removed)
        {
            Votes.Remove(remove);
        }

        foreach (var (action, list) in currentVotes)
        {
            var count = list.Count;

            if (action.Icon == null)
                return;

            if (!Votes.TryGetValue(action, out var control))
            {
                control = new GhostGroupCounter(action.Color);
                Votes.Add(action, control);
                Container.AddChild(control);
                control.Icon.Texture = _spriteSystem.Frame0(action.Icon);
            }

            control.SetText(count, required);

            if (count == 0)
            {
                Container.RemoveChild(control);
                Votes.Remove(action);
            }
        }
    }
}


