using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._UM.Drip.UI;

[GenerateTypedNameReferences]
public sealed partial class DripDrobeEntry : Control
{
    public DripDrobeEntry(EntProtoId protoId, string name, string description, int amount)
    {
        RobustXamlLoader.Load(this);

        ItemView.SetPrototype(protoId);

        ItemName.Text = name;

        ItemDescription.SetMessage(description);
    }
}

