using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._UM.Drip.UI;

public record DripDrobeListData(String Entry, int Amount) : ListData;

[GenerateTypedNameReferences]
public sealed partial class DripDrobeWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly StyleBoxFlat _styleBox = new() { BackgroundColor = new Color(70, 73, 102) };

    public DripDrobeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

    }

    private void CreateItem(string item, int amount)
    {
        if (!_prototypeManager.TryIndex(item, out var prototype))
            return;

        var entry = new DripDrobeEntry(prototype, prototype.Name, prototype.Description, amount);

        ProgramList.AddChild(entry);

    }

    public void Populate(IReadOnlyDictionary<string, int> items)
    {
        foreach (var item in items)
        {
            CreateItem(item.Key, item.Value);
        }
        //VendingContents.PopulateList(listData);
    }

}

